
services:
  web-server:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "5173"
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/ca_bundle.crt:/etc/ssl/ca_bundle.crt
      - ./ssl/certificate.crt:/etc/ssl/certificate.crt
      - ./ssl/private.key:/etc/ssl/private.key