name: Github Workflow

on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy
        run: |
          sudo docker compose -f docker-compose.yaml -p nlp down --rmi all
          sudo docker compose -f docker-compose.yaml -p nlp up -d